# Generated by Django 4.2 on 2023-05-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read_log", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readlog",
            name="operation",
            field=models.TextField(
                choices=[
                    ("detail", "Detail view, directly targeted"),
                    (
                        "list",
                        "List view, was part of the result list for a list/search view",
                    ),
                    (
                        "update",
                        "Update view, the object was displayed as part of editing the object.",
                    ),
                    (
                        "delete",
                        "Delete view, the object was displayed as part of deleting the object.",
                    ),
                ]
            ),
        ),
    ]
